#include<stdio.h>
#include<stdlib.h>
#include<time.h>
#include<string.h>
char list[1000][8];
int cnt=0;
int add(){
	char masuk[101];
	srand(time(NULL));
	printf("\nLicense Plate Format: XXXXYYY\n");
	printf("X => [0 - 9]\nY => [A - Z]\nPlate must be unique\ntype 'random' to insert random plate generated by the system\n\nInsert new plate: ");
	scanf("%s",masuk);
	if(masuk[0]=='r'&&masuk[5]=='m'){
		for(int a=0;a<=3;a++){
			masuk[a]=char(rand()%10+48);
		}
		for(int a=4;a<=6;a++){
			masuk[a]=char((rand()%26)+65);
		}
		
	}
	if(false){
		printf("This plate already registered!");
	}
	else{
		printf("Plate '%s' Inserted",masuk);
		strcpy(masuk,list[cnt]); cnt++;
	}
	getchar(); getchar();
}
int main(){
	int choice;
	printf("License Plate Organizer\n\n");
	printf("1. Add New License Plate\n");
	printf("2. View All Plates\n");
	printf("3. Clear All Plates\n");
	printf("4. Exit\n\n");
	printf("Input [1-4]: ");
	scanf("%d",&choice);
	getchar();
	
	if(choice==1){
		system("cls");
		add();
		system("cls");
		main();	
	}
	else if(choice==2){
		system("cls");
		//view();
		main();
	}
	else if(choice==3){
		system("cls");
		//clear();
		main();
	}
	else exit;
}
